// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzlwlwhuydbsqvcfack.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4emx3bHdodXlkYnNxdmNmYWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTQ4NTAsImV4cCI6MjA2OTMzMDg1MH0.sCphlHWCQAZbXCKRhLjHnKGsNGcMRTPou_ZFNTlAmWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});